### ISSUE TITLE
0.1 вынести в переменную и обозвать

### ISSUE THREAD

**Issue by coursar** [AnastasiaBezb/02_homework_wallpaper#1]
https://github.com/AnastasiaBezb/02_homework_wallpaper/blob/a187ec0d8370f6e53735b894ddc4ada7fcc28382/lib.py#L11

**Comment by AnastasiaBezb** [comment]
https://github.com/AnastasiaBezb/02_homework_wallpaper/blob/ec9218a4c23d1c52c9ab54d2b1b8c10a389a8568/lib.py#L7-L10 сделано

**Comment by coursar** [comment]
issue нужно закрывать сообщениями в коммитах, а не комментариями к issue
